### ISSUE TITLE
Add django.contrib.gis to installed apps

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/django-project-template#48]
'django.contrib.gis',

**Comment by aboutaaron** [comment]
Is this not being recognized? https://github.com/cirlabs/django-project-template/blob/master/project_name/settings/common.py#L72

**Comment by aboutaaron** [comment]
I mean, we almost always use Postgis so I can just make it a default and not have a flag

**Comment by aboutaaron** [comment]
:+1:
