### ISSUE TITLE
Add core app for CIR fancypants stuff

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/django-project-template#50]
In our old template we had the core app, which added lots of nifty reusable stuff.

**Comment by mikejcorey** [comment]
See also: https://github.com/cirlabs/pesticides/tree/master/pesticides/apps/core

**Comment by aboutaaron** [comment]
I moved core into the `lib` dir: https://github.com/cirlabs/django-project-template/tree/master/lib

I did just to clean up apps and keep it project focused. Feel free to readjust if you'd like it to go back to the OG way

**Comment by mikejcorey** [comment]
Your way makes more sense.
