### ISSUE TITLE
Fabfile.py: Switch order of gzip_assets and grunt_build in def deploy

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/django-project-template#59]
Otherwise things moved or generated in the gruntfile won't get gzipped and sent on.

**Comment by aboutaaron** [comment]
Nice catch. I'll push the change later today. 

-----
Aaron Williams
Journalist/Developer
@aboutaaron




On Mon, Feb 2, 2015 at 12:06 PM -0800, "Michael Corey" <notifications@github.com> wrote:












Assigned #59 to @aboutaaron.
